core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.IndexView.as_view(),name = 'index'),
    path('add/',views.AddView.as_view(),name = 'add'),
    path('posts/',views.PostsView.as_view(),name = 'posts'),
    path('<slug:slug>/',views.SingleView.as_view(),name = 'single'),
    path('edit/<int:pk>/',views.EditView.as_view(),name = 'edit'),
    path('delete/<int:pk>/',views.Delete.as_view(),name = 'delete'),
]

djangoCrudProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
]

core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Core(models.Model):
    title = models.CharField(max_length=200)
    excerpt = models.TextField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=100,unique=True)
    update = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('core:single', args=[self.slug])

    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.title

core/views.py
from .models import Core
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy


class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'


class SingleView(DetailView):
    model = Core
    template_name = 'core/single.html'
    context_object_name = 'post'


class PostsView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'


class AddView(CreateView):
    model = Core
    template_name = 'core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('core:posts')


class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')


class Delete(DeleteView):
    model = Core
    template_name = 'core/confirm-delete.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')

templates/core/add.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group md-3">
            <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button name="save" type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Save
            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-danger">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>CRUD app</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    {% include 'core/navbar.html' %}
    {% block content %}
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>

  {% include 'core/footer.html' %}
  </body>
</html>

templates/core/confirm-delete.html
{% extends 'core/base.html' %}
{% block content %}

<div class="container pt-5">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input name="confirm" type="submit" value="Confirm">
    </form>
</div>

{% endblock %}

templates/core/edit.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="container pt-5">
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                <span class="glyphicon glyphicon-ok"></span> Edit
            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

templates/core/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-dark text-muted">
  <!-- Section: Social media -->
  <section
    class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
  >
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Java</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Kotlin</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Dart</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Flutter</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i> Elephant Road, Dhaka-1205, BD</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            ssk123098@gmail.com
          </p>
          <p><i class="fas fa-phone me-3"></i> +880 1740537161</p>
          <p><i class="fas fa-print me-3"></i> +880 1520103756</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="#">CRUD APP by Sizan</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for core in index %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg" alt="Card image Cap">
                            <div class="card-body">
                                <h4 class=""><a href="{{ core.get_absolute_url }}">{{ core.title }}</a></h4>
                                <p class="card-text"></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="">
                                        <small class="text-muted">{{ core.published }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-danger">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CRUD App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'core:posts' %}">Manage Posts</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/core/posts.html
{% extends 'core/base.html' %}

{% block content %}

    <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Post Administration</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
              <a class="nav-link" id="add" href="{% url 'core:add' %}">Add New</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

   <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for post in post_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg" alt="Card image Cap">
                            <div class="card-body">
                                <h4 style="font-weight: bold;color: darkmagenta" class="lead">{{ post.title }}</h4>
                                <p class="card-text"></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn">
                                        <a href="{{ post.get_absolute_url }}" name="view" class="btn btn-md btn-outline-primary" role="button" aria-pressed="true">View</a>
                                        <a href="{% url 'core:edit' post.pk %}" name="edit" class="btn btn-md btn-outline-warning" role="button" aria-pressed="true">Edit</a>
                                        <a href="{% url 'core:delete' post.pk %}" name="delete" class="btn btn-md btn-outline-danger" role="button" aria-pressed="true">Delete</a>
                                    </div>
                                    <small class="text-muted">{{ post.published }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/core/single.html
{% extends 'core/base.html' %}

{% block content %}
{#    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">#}
{#        <div class="navbar-brand">Post Administration</div>#}
{#        <div class="collapse navbar-collapse" id="navbarNav">#}
{#            <ul class="navbar-nav">#}
{#                <li class="nav-item active">#}
{#                    <a class="nav-link" href="{% url 'core:add' %}">Add New</a>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
{#    </nav>#}

    <nav class="navbar navbar-expand-lg navbar-light bg-info">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Post Administration</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
              <a class="nav-link" href="{% url 'core:add' %}">Add New</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

   <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for post in post_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="https://cdn.pixabay.com/photo/2018/01/14/23/12/nature-3082832__480.jpg" alt="Card image Cap">
                            <div class="card-body">
                                <h4 style="font-weight: bold;color: darkmagenta" class="lead">{{ post.title }}</h4>
                                <p class="card-text"></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn">
                                        <a href="{{ post.get_absolute_url }}" class="btn btn-md btn-outline-primary" role="button" aria-pressed="true">View</a>
                                        <a href="{% url 'core:edit' post.pk %}" class="btn btn-md btn-outline-warning" role="button" aria-pressed="true">Edit</a>
                                        <a href="{% url 'core:delete' post.pk %}" class="btn btn-md btn-outline-danger" role="button" aria-pressed="true">Delete</a>
                                    </div>
                                    <small class="text-muted">{{ post.published }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}